AllCops:
    TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/ClassLength:
  Severity: warning

Metrics/LineLength:
  Max: 100
  Severity: warning

Metrics/MethodLength:
  Max: 12
  Severity: warning

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/yle_tf-*.rb'
    - 'spec/yle_tf-*_spec.rb'

Style/GuardClause:
  MinBodyLength: 3

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
